### ISSUE TITLE
Import python packages declared in iPythonWith.packages doesn't work

### ISSUE THREAD

**Issue by rollf** [tweag/jupyterWith#109]
**Describe the bug**
I am unable to import python packages within notebook cells although these have been added to the ipython kernel.
I expect that this is not a bug but rather a misunderstanding from my side.

**To Reproduce**

Use this ``shell.nix``:

```
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "69a1d5e544dd23fc64cef91249872e0048279bec";
  }) {};

  iPython = jupyter.kernels.iPythonWith {
    name = "python";
    packages = p: with p; [
      numpy
      seaborn
    ];
  };

  jupyterEnvironment = jupyter.jupyterlabWith {
    extraPackages = p: [p.python37Packages.jupytext p.python37Packages.numpy];
    extraJupyterPath = pkgs: "${pkgs.python37Packages.jupytext}/lib/python3.7/site-packages:${pkgs.python37Packages.numpy}/lib/python3.7/site-packages";
    # This works:
    # extraJupyterPath = pkgs: "${pkgs.python37Packages.jupytext}/lib/python3.7/site-packages:${pkgs.python37Packages.numpy}/lib/python3.7/site-packages:${pkgs.python37Packages.seaborn}/lib/python3.7/site-packages";
    kernels = [ iPython ];
  };
in
  jupyterEnvironment.env
```
Run with ``nix-shell --command "jupyter lab"``.

**Expected behavior**
``import seaborn`` should work in Jupyter but I get ``ModuleNotFoundError: No module named 'seaborn'``.
Importantly,  `` import numpy`` works fine. I got it working by adding it to ``extraJupyterPath`` but this surely not the way it should work.

**Environment**
 - OS name + version:
Linux heulSUSE 4.12.14-lp151.28.52-default #1 SMP Wed Jun 10 15:32:08 UTC 2020 (464fb5f) x86_64 x86_64 x86_64 GNU/Linux
 - Version of the code:
69a1d5e544dd23fc64cef91249872e0048279bec

**Comment by guaraqe** [comment]
Before I check, when you start JupyterWith, there should be two python kernels: the one that comes by default, which is empty, and a second one which should have the name you gave, "Python - python" in this case. Do you confirm you are using the second one?

**Comment by rollf** [comment]
I used the wrong Kernel. Perfect, thanks so much. I was expecting some problem on my side.
