### ISSUE TITLE
Add a Cachix cache

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#12]
This would make the setup faster both for users and for the test suite, since it has to rebuild everything everytime.

**Comment by MMesch** [comment]
Yes, it would be nice to have everything cached even on the first run!

**Comment by guaraqe** [comment]
This was just implemented. The only exception seems to be `cabal2nix`, which has to be rebuild. This is because of import-from-derivation being used on `callCabal2nix`.
