### ISSUE TITLE
shelly did not find ghc-pkg

### ISSUE THREAD

**Issue by jamesdbrock** [tweag/jupyterWith#127]
**Describe the bug**

On launching an IHaskell kernel,

```
[I 14:43:01.653 LabApp] Kernel started: 821de465-a8c0-41fe-8253-5fabf144cc35
ihaskell: 
Ran commands: 
ghc-pkg check
which ghc-pkg

Exception: user error (shelly did not find ghc-pkg in the PATH: 
```

**To Reproduce**

```
nix-shell --command 'jupyter lab'
```
with the recommended `shell.nix` from https://github.com/tweag/jupyterWith#getting-started

**Environment**
 - OS name + version: Fedora 32
 - Version of the code: Current *master*

**Additional context**

**Comment by jamesdbrock** [comment]
This should probably be fixed in `kernels/ihaskell/default.nix`, but I'm not sure how that would be done while ensuring that multiple Haskell kernels with different GHC versions don't collide, as in https://github.com/tweag/jupyterWith/commit/31f49b66bc2f07230f6bd27436eb21f77241d4c9#diff-0bb44541ee6761fe038dffc9a29af775

**Comment by guaraqe** [comment]
In the case of a single kernel, I have the impression that only making GHC accessible through `extraPackages` should be enough. Can you confirm?

For more than one kernel, this can be more complicated. How much Shelly relies on GHC? I don't understand very well why it depends on the executable.

**Comment by jamesdbrock** [comment]
> In the case of a single kernel, I have the impression that only making GHC accessible through `extraPackages` should be enough. Can you confirm?

Yes, confirmed.

> For more than one kernel, this can be more complicated. How much Shelly relies on GHC? I don't understand very well why it depends on the executable.

Yeah, why? I don't understand either.

**Comment by jamesdbrock** [comment]
Oh I should note that in my Jupyter Launcher, there are two Haskell kernels

1. __Haskell__ has this missing `ghc-pkg` problem
2. __Haskell - haskell__ does not have this problem

**Comment by jamesdbrock** [comment]
Actually never mind, I was seeing this error on a dangling system-wide kernel in `~/.local/share/jupyter/kernels/haskell`. The __Haskell - haskell__ kernel works fine.
