### ISSUE TITLE
jupyter serverextension

### ISSUE THREAD

**Issue by jamesdbrock** [tweag/jupyterWith#131]
I'm trying to work out how to install a Jupyter serverextension, specifically https://github.com/yuvipanda/nbresuse which is required for the labextension https://github.com/jtpio/jupyterlab-system-monitor .

I'm looking at https://github.com/tweag/jupyterWith/issues/86 , which is very helpful, but I'm not sure how to accomplish the step where I would `jupyter serverextension enable nbresuse` and incorporate that into the `jupyterWith` derivation.

I think maybe I would need a `jupyterlabWith` parameter `extraPythonPath` so that I could add `nbresuse` to the arguments to `makePythonPath`?

https://github.com/tweag/jupyterWith/blob/35eb565c6d00f3c61ef5e74e7e41870cfa3926f7/default.nix#L33-L38

Does anyone have any advice or examples? 

## Other References

https://nixos.wiki/wiki/Python

https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html

https://functor.tokyo/blog/2019-03-16-nix-derivation-for-fastai

> So there is `mkDerivation`, `buildPythonPackage` and `buildPythonApplication`. There are also `toPythonModule` and `toPythonApplication`. https://github.com/NixOS/nixpkgs/issues/40835#issuecomment-391822714

> “you should avoid using PYTHONPATH” https://discourse.nixos.org/t/get-pythonpath-from-pkgs-python3-withpackages/6076

**Comment by jamesdbrock** [comment]
I broke my serverextension attempt out into an isolated git branch. This is what I'm trying, it doesn't work yet.

https://github.com/jamesdbrock/jupyterWith/blob/try-system-monitor/shell.nix

**Comment by jamesdbrock** [comment]
Ok this works. For anyone else who wants to do this, here's an examples `shell.nix`:

```nix
{ overlays ? []
, config ? {}
, pkgs ? import ./nix { inherit config overlays; }
}:

let
  jupyter = import ./default.nix { inherit config overlays pkgs; };

  iPython = jupyter.kernels.iPythonWith {
    name = "python";
    packages = p: with p; [ numpy ];
  };

  # https://github.com/yuvipanda/nbresuse
  # Needed for jupyterlab-system-monitor
  nbresuse = pkgs.python3Packages.buildPythonPackage rec {
    pname = "nbresuse";
    version = "0.3.6";
    src = pkgs.python3Packages.fetchPypi {
      inherit pname version;
      sha256 = "13p9chk341iy78zwa2vmrnqkysi70wpxlk5kmrq99wcgn389v8av";
    };
    propagatedBuildInputs = with pkgs.python3Packages; [ notebook psutil mock ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [ iPython ];
      directory = jupyter.mkDirectoryWith {
        extensions = [
          "jupyterlab-topbar-extension@0.5.0"
          "jupyterlab-system-monitor@0.6.0"
        ];
      };
      extraPackages = p: [ nbresuse pkgs.python3Packages.psutil ];
      extraInputsFrom = _: [ nbresuse ];
      extraJupyterPath = _: "${nbresuse}/lib/python3.7/site-packages:${pkgs.python3Packages.psutil}/lib/python3.7/site-packages";
    };
in
  jupyterEnvironment.env
```

Run with 
```
nix-shell --option sandbox false --command 'jupyter lab --ResourceUseDisplay.track_cpu_percent=True'
```

**Comment by guaraqe** [comment]
Oh, nice to see you solved this alone. Do you think that adding a link to your example to the README would help others?

**Comment by jamesdbrock** [comment]
> Do you think that adding a link to your example to the README would help others?

Yeah, I hope it would. You're welcome to link to it from the README if you like.
