### ISSUE TITLE
Request dotnet-interactive kernel

### ISSUE THREAD

**Issue by devhell** [tweag/jupyterWith#140]
Hi,
I'm curious if the .Net Interactive kernels for C# and perhaps F# can be added: https://github.com/dotnet/interactive/

I'm not at all clear on the state of `dotnet` in `nixpkgs`, and so I'm not sure what, if anything, is missing to make this kernel available.

Thank you!

**Comment by garbas** [comment]
We don't have any plans to add dotnet kernel at this point. But if somebody want to add it we would be glad to help package it.
