### ISSUE TITLE
question regarding ihaskell's built-in auto-completion functionality:

### ISSUE THREAD

**Issue by zeta-00** [tweag/jupyterWith#141]
Hello There,

Does jupyterWith provide ihaskell's built-in auto-completion out-of-the-box? I have not been able to get it to work with Emacs-IPython-Notebook, I've only been able to get IHaskell's built-in auto-completion functionality to work in Atom with it's Hydrogen package. Here's my corresponding reddit question for this, if you'd like to take a look:

https://www.reddit.com/r/haskell/comments/l3rabd/how_do_you_get_ihaskells_builtin_autocompletion/

Thanks in advance for the help!

**Comment by garbas** [comment]
We currently don't have it working, but it is on our roadmap to get to it at some point.
