### ISSUE TITLE
Add Ocaml Kernel (using ocaml-jupyter)

### ISSUE THREAD

**Issue by fusetim** [tweag/jupyterWith#162]
**Is your feature request related to a problem? Please describe it.**
I would like to use Ocaml in my jupyter notebooks, because I will have to do some in college. So I searched for an ocaml kernel for jupyter, found ocaml-jupyter and made a derivation for it.
But since I am new to NixOS and Nix, I might need help structuring this kernel before creating a PR.

**Describe the solution you want**
Have a new Ocaml kernel in JupyterWith using ocaml-kernel.

**Describe the alternatives you have considered**
I created an Ocaml kernel for JupyterWith, here https://gist.github.com/fusetim/e59b17fc9bac31f2e43174fccd14d7e9.
And I am currently using it with this jupyterEnvironment: https://gist.github.com/fusetim/0b0534b3d451bce6aabb5a69a42b8ed4.

**Comment by guaraqe** [comment]
If your kernel is working already with JupyterWith, that's very nice! If you want to open a PR, I recommend to:

- Add your kernel to the `kernels` folder, more or less following the model of the other kernels
- Add a test (the simplest notebook you can think about) in the `example` folder
- Add it to the list of kernels in `tests/default.nix`, for example at line 60.

By doing this and opening a PR, it will be automatically tested, which will help you find errors and help me review it.
