### ISSUE TITLE
flake devshell does not contain generate-directory

### ISSUE THREAD

**Issue by nothingmuch** [tweag/jupyterWith#166]
### Problem description

On NixOS unstable, with flakes enabled, using `nix develop` in the example directory results in a shell environment that still can't actually run jupyterlab.

### Steps to replicate

This can be replicated on 6024eb9329c5f47102adc26f541712121bba62d4 by running `nix flake --update` in `examples/flake`, and then `nix develop`. No `.jupyterlab` directory is built, `generate-directory` is not in the path, and `jupyter lab build` fails because node is not available.

After I updated `flake.lock` had the following changes:

```diff
diff --git a/example/flake/flake.lock b/example/flake/flake.lock
index 4667169..6c90e94 100644
--- a/example/flake/flake.lock
+++ b/example/flake/flake.lock
@@ -2,11 +2,11 @@
   "nodes": {
     "flake-utils": {
       "locked": {
-        "lastModified": 1623875721,
-        "narHash": "sha256-A8BU7bjS5GirpAUv4QA+QnJ4CceLHkcXdRp4xITDB0s=",
+        "lastModified": 1629481132,
+        "narHash": "sha256-JHgasjPR0/J1J3DRm4KxM4zTyAj4IOJY8vIl75v/kPI=",
         "owner": "numtide",
         "repo": "flake-utils",
-        "rev": "f7e004a55b120c02ecb6219596820fcd32ca8772",
+        "rev": "997f7efcb746a9c140ce1f13c72263189225f482",
         "type": "github"
       },
       "original": {
@@ -36,7 +36,7 @@
         "nixpkgs": "nixpkgs"
       },
       "locked": {
-        "narHash": "sha256-OUfD1rMoUsoESbOgpVtNtuIz5dUD8dJM/ktPNEzh++E=",
+        "narHash": "sha256-L+VsaGYdQ/DeZ/3BUeMtexADIlzTNFNYPrRreAKoUzo=",
         "path": "../../.",
         "type": "path"
       },
```

This was necessary since the top level flake for `jupyterWith` itself was out of sync with the example directory.

### Workaround?

Modifying `devshell.nix` I was able to work around this, giving access to `generate-directory` and allowing `jupyter-lab build` to work. This feels really wrong but seemed to work I guess

```diff
diff --git a/example/flake/devshell.nix b/example/flake/devshell.nix
index 4a2c833..56f0a30 100644
--- a/example/flake/devshell.nix
+++ b/example/flake/devshell.nix
@@ -21,6 +21,7 @@ in
 pkgs.mkShell rec {
   buildInputs = [
     jupyterEnvironment
+    jupyterEnvironment.env.buildInputs
   ];

   shellHook = ''
```

**Comment by SenchoPens** [comment]
Hi, a more flake-y way, without devshell.nix (which purpose I do not understand XD):

```diff
diff --git a/example/flake/flake.nix b/example/flake/flake.nix
index 9e5c410..0ea3d34 100644
--- a/example/flake/flake.nix
+++ b/example/flake/flake.nix
@@ -49,6 +49,8 @@
         };
 
         defaultPackage = self.packages.${system}.jupyterEnvironment;
+
+        defaultPackage = self.packages.${system}.jupyterEnvironment.devShell;
       }
       )
     ) // {
```

P.S. IMO the example and the project flake both have a bit of old-school-nix parts, I hope I would find time to submit my improvements next week.
