### ISSUE TITLE
feature: Typescript Kernel

### ISSUE THREAD

**Issue by nazzacode** [tweag/jupyterWith#169]
As the title suggests. A TypeScript kernel using `ts-lab` would be an amazing addition.

**Comment by nazzacode** [comment]
I would love to try and implement this myself but am not sure if this is realistic with my level of nix experience. Let me know if you think this is possible?

**Comment by guaraqe** [comment]
Hello! Creating a kernel is not very difficult -- it consists on packaging that gives the kernel executable (or finding it on Nixpkgs), and writing a kernel file. Each one of the subfolder in the `kernels` folder is an example of package. If you want to try, I recommend choosing one of the smallest definitions, and to try replication it for `ts-lab`.

**Comment by djacu** [comment]
@nazzacode 
There is a PR #259 to add a Typescript kernel. I believe it works. Give it a try if you have a chance.
