### ISSUE TITLE
Unicode support in iHaskell 

### ISSUE THREAD

**Issue by emeinhardt** [tweag/jupyterWith#175]
**Describe the bug**
iHaskell notebooks launched using `jupyterWith` yield errors when I attempt to print Unicode.

**To Reproduce**

1. Follow instructions in the `jupyterWith` README to set up a repository for `jupyterWith` and start a JupyterLab server. It does not matter if one chooses to go through steps to add JupyterLab extensions or not. Alternatively, `cd` into `jupyterWith/example/Haskell`.

2. Open an existing iHaskell notebook that prints non-ASCII Unicode, or start a new notebook/console that does the same (e.g. `putStrLn "©"`). Trying `putStrLn "©"`in `jupyterWith/example/Haskell/test.ipynb` should suffice. 

You should get
```
<stdout>: hPutChar: invalid argument (invalid character)
```

In contrast, Python notebooks launched from the same JupyterLab server have no such trouble, neither does the `ghci` instance installed by `nix` system-wide, and iHaskell set up via `stack` on macOS 9 months ago also has no such issue.

**Expected behavior**
A string representation containing appropriate Unicode should be printed as output and rendered as a Unicode character.

**Environment**
 - OS name + version:
```
OS: NixOS 21.05 (Okapi) x86_64
Kernel: 5.14.8
```
 - Version of the code: 
   - `jupyterWith`: Whatever version of `jupyterWith` is pulled by following the instructions in the README right now.
   - `iHaskell`/`GHC`: `0.10.2.0`/`8.10.4` is what ends up being built and launched on my machine.

**Additional context**
For the purpose of eliminating possible alternative explanations, I've set my preferred serif/sans/mono fonts to be DejaVu Serif/Sans/Sans Mono in Firefox and Brave (a chromium variant), and in my JupyterLab preferences. (DejaVu ___ has good unicode support.) This did not change reproducibility of the bug on my end.

**Comment by guaraqe** [comment]
I cannot reproduce locally, also on NixOS and Firefox. Is this the first time you use JupyterWith? If not, try setting the commit to be sure to get the latest version.

```nix
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "73bdac9ca036c0303fc3a487129e23f9c4ad0bcf";
  }) {};
```
