### ISSUE TITLE
How to disable ipykernel / configure it?

### ISSUE THREAD

**Issue by doronbehar** [tweag/jupyterWith#181]
I'd like to configure a jupyter environment and I'd like it to present only a single python Notebook in the launcher. Currently, if I use:

```nix
devShell = (jupyterlabWith {
  kernels = [];
}).env
```

I still see `ipykernel` in the launcher:

![Screenshot from 2021-12-14 22-17-43](https://user-images.githubusercontent.com/10998835/146073113-53c7d2ee-28ba-489e-8ce2-1f19592e546b.png)

And if I use:

```nix
devShell = (jupyterlabWith {
  kernels = [
    (kernels.iPythonWith {
      name = "python";
      packages = p: [p.pint];
    })
  ];
}).env
```

I get another python launcher:

![Screenshot from 2021-12-14 22-21-48](https://user-images.githubusercontent.com/10998835/146073677-10c8f890-7580-41ac-8d98-757c05db4105.png)

And I noticed that the python module `pint` is not available in the `ipykernel` notebook, but it is available in the right launcher.

How do I disable the `ipykernel` launcher?

**Comment by GTrunSec** [comment]
please try:

```
jupyter lab --KernelSpecManager.ensure_native_kernel=False
```

**Comment by guaraqe** [comment]
The first time I tried removing this kernel, I failed, but this is something I would like for some time.

@GTrunSec Is this a new flag? If this works, we could add it by default.

**Comment by GTrunSec** [comment]
> Is this a new flag? If this works, we could add it by default.
Sure, It works. you can find all of the settings in the config file of jupyter. which means you can do either flag or put it in the config file(`~/.jupyter/jupyter_notebook_config.py   `)

**Comment by doronbehar** [comment]
> The first time I tried removing this kernel, I failed, but this is something I would like for some time. Like 1/3 of the issue reports are about Python packages not working because people clicked on the wrong kernel.

I think this is a Nixpkgs issue. I also failed to trace the source of this kernel there but perhaps that's possible with some effort. @FRidh since you maintain some of jupyter's related packages in Nixpkgs perhaps you could help here please?
