### ISSUE TITLE
Is it possible to use this with a flake-configured system? 

### ISSUE THREAD

**Issue by JonathanReeve** [tweag/jupyterWith#187]
I see that there's a flake.nix here, and even some flake usage examples, but I'm at a loss for how to integrate this with my system's flake.nix. Here's what I have so far: 

```nix
{
  description = "My NixOS configuration.";
  inputs = {
    nixos.url = "nixpkgs/nixos-unstable";
    jupyterWith.url = "github:tweag/jupyterWith";
  };
  outputs = { self, nixos, jupyterWith}: {
    nixosConfigurations.jon-laptop = nixos.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [ ./configuration.nix
                  jupyterWith.jupyterlabWith { kernels = [
                                                 (jupyterWith.kernels.iPythonWith {
                                                   name = "python";
                                                   packages = p: with p; [ pandas ];
                                                 })
                                                 (jupyterWith.kernels.iRWith {
                                                   name = "R";
                                                   packages = p: with p; [ ggplot2 ];
                                                 })
                                               ]; }
                ];
    };
  };
}
```

I've also tried using `jupyterWith.jupyterEnvironment`, but none of these attributes seem to exist. Am I doing something wrong?

**Comment by ParetoOptimalDev** [comment]
You have to use the overlay method I think. I got it partially working before hitting #184

**Comment by kirelagin** [comment]
`jupyterWith.jupyterlabWith` is essentially a package – it has a `/bin` directory and so on. So, you can just install it as a regular package, e.g. to have it available globally, you can add it to `environment.systemPackages`.

So, the easiest way would be to do something like:

```nix
let jenv = jupyterWith.jupyterlabWith { ... };
```

and then add a trivial module to the `modules` attribute of the system configuration you are building:

```nix
{
  # ...
  modules = [
    ./configuration.nix
    { environment.systemPackages = [ jenv ]; }
  ];
  #...
}
```

**Comment by kirelagin** [comment]
oh, yes, right, and you do need to go all the way via overlays....

**Comment by malteneuss** [comment]
It would be nice to have a full flake example in the docs.

**Comment by garbas** [comment]
This will be fixed and documented with next version of jupyterWith (see main branch)

**Comment by ParetoOptimalDev** [comment]
@garbas Was "using jupyterWith" from a flake system configuration documented? I don't see any example in the docs folder.

I tried the examples that are there and they work wonderfully.
