### ISSUE TITLE
generate-directory broken (--app-dir)

### ISSUE THREAD

**Issue by kirelagin** [tweag/jupyterWith#188]
**Describe the bug**

```text
$ generate-directory jupyterlab_bokeh
Generating directory './jupyterlab' with extensions:
- jupyterlab_bokeh
usage: jupyter-labextension [-h] [--debug] [--show-config] [--show-config-json] [--generate-config] [-y] [--log-level LabExtensionApp.log_level] [--config LabExtensionApp.config_file] [extra_args ...]
jupyter-labextension: error: unrecognized arguments: --app-dir=./jupyterlab
```

**To Reproduce**

* `generate-directory jupyterlab_bokeh`

**Expected behavior**

It should work.

**Environment**
 - NixOS 21.11
 - 36b627983b38c5c66b945b4c3ab4aa9b49adfa64

**Comment by kirelagin** [comment]
Looking at the code, and assuming that we want the config file placed in `./jupyterlab` with the default name, the most reasonable way to do this is `--config="$(pwd)/jupyterlab/jupyter labextension_config.py"`.

**Comment by kirelagin** [comment]
Nevertheless, this command does not seem to do anything related to the actual extension it is supposed to install.

**Comment by kirelagin** [comment]
```text
$ /nix/store/fcllvq8h1xawysxq7qjjw9w2c9p4xb7v-python3.9-jupyterlab-3.2.6/bin/.jupyter-labextension-wrapped install "jupyterlab_bokeh" --KernelSpecManager.ensure_native_kernel=False --config="$(pwd)/jupyterlab/jupyter labextension_config.py"
An error occurred.
OSError: [Errno 30] Read-only file system: '/nix/store/fcllvq8h1xawysxq7qjjw9w2c9p4xb7v-python3.9-jupyterlab-3.2.6/share/jupyter/lab/extensions'
See the log file for details:  /run/user/1000/jupyterlab-debug-ff3r3p4g.log
```

**Comment by kirelagin** [comment]
Oh well, it wants `app_dir` too.

**Comment by kirelagin** [comment]
Also, apparently `--generate-config` doesn’t do anything in conjunction with `install`. Is it really needed?

**Comment by kirelagin** [comment]
Ah, ok, I see, `--app-dir` _does_ work, assuming that the `install` command is recognised.

**Comment by Etjean** [comment]
Thnaks for pointing that out. I guess we need to remove the `--KernelSpecManager.ensure_native_kernel=False` option that is automatically added with `juppyter-labextension`.

**Comment by Etjean** [comment]
@kirelagin, When able, could you check that the PR above fixes this issue?
