### ISSUE TITLE
how can this be run on non-nixos-plattforms?

### ISSUE THREAD

**Issue by deknos** [tweag/jupyterWith#208]
**Is your feature request related to a problem? Please describe.**
I want to run this within docker on other plattforms than nix. for example debian or opensuse. How can i do that?

i want to use nixos more, but before everything migrating to nix os, i want to run stuff within virtual machines and docker to ease the migration. because of that this would be very nice.

**Describe the solution you'd like**
Is there a howto with an nixos-standard-docker-image and your code which i can run for example with docker-compose so that i have such an environment?

**Comment by Ryunaq** [comment]
You only need nix, not nixos. See the official page for guidance https://nixos.org/download.html
