### ISSUE TITLE
unable to use the suggested shell.nix (as git too old?)

### ISSUE THREAD

**Issue by DougBurke** [tweag/jupyterWith#26]
I have nix-2.2.1 (also seen with nix-2.1.3) and with the README-suggested `shell.nix` (shown below) I get the following failure:

```
% nix-shell
nix-shell
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
error: program 'git' failed with exit code 129
```

My guess is that it's using the system `git` which is not particularly modern (and I can't easily update):

```
% git --version
git version 1.8.3.1
```

I assume there's a way for me to tell nix to install its own `git` and use that, but I am a nix neophyte and have no idea how to do this, so any help would be greatly appreciated (I also understand that this is not a jupyterWith problem directly).

For reference, the `shell.nix` I used is:

```
% cat shell.nix
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "";
  }) {};

  iPython = jupyter.kernels.iPythonWith {
    name = "python";
    packages = p: with p; [ numpy ];
  };

  iHaskell = jupyter.kernels.iHaskellWith {
    name = "haskell";
    packages = p: with p; [ hvega formatting ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [ iPython iHaskell ];
    };
in
  jupyterEnvironment.env
```

**Comment by zimbatm** [comment]
to add git to your user profile, run:
```sh
nix-env -f https://github.com/nixos/nixpkgs-channels/archive/nixos-18.09.tar.gz -iA git
```

**Comment by DougBurke** [comment]
Thanks. Out of interest us there a way to just do this in the `shell.nix` file, so I don't have it in my user profile (in part because I've just found out that the system git is appearing in my path before the nix profile so I need to look at my path set up, but also because I may not want to add it to my user profile)?

**Comment by DougBurke** [comment]
I'm going to close this now since I have been able to get `nix-shell` to start it's work, as shown below. Thanks for your help @zimbatm 

```
% nix-shell
unpacking 'https://github.com/NixOS/nixpkgs/archive/2a051165d53585630a602e831496f7157c519885.tar.gz'...
copying path '/nix/store/4w2hq9izk2dnqs9xrllyn2bx4yp4l82k-glibc-locales-2.27' from 'https://cache.nixos.org'...
copying path '/nix/store/5bj8yfpgi240w8x56visxck9qsvib1mh-abstract-deque-0.3.tar.gz' from 'https://cache.nixos.org'...
copying path '/nix/store/wc0sshipvsfzkaxhx221bnl84pk1fi2m-abstract-par-0.3.3.tar.gz' from 'https://cache.nixos.org'...
...
... many more lines
...
... oh, now the compilation begins ;-)
...
... even-more lines
...
```

**Comment by zimbatm** [comment]
yeah make sure that your user profile appears first in the PATH. this should be the default, not sure why your environment doesn't do the right thing.

the issue is that `builtins.fetchGit` happens at evaluation time, before nix is able to control any environment. one possibility is to swap to use `builtins.fetchTarball` if the service serves a tarball as well (GitHub does)
