### ISSUE TITLE
Error build: upgrade python 3.9 to 3.10

### ISSUE THREAD

**Issue by PlumpMath** [tweag/jupyterWith#261]
Python is now 3.10 by default on nixpkgs.
nix-darwin & linux(nixos) 

error: builder for '/nix/store/33awsap39k9km6mjp244vvqr3i645zw0-python3.10-nbconvert-6.5.0.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.macosx-10.12-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /private/tmp/nix-build-python3.10-nbconvert-6.5.0.drv-0/nbconvert-6.5.0/dist /private/tmp/nix-build-python3.10-nbconvert-6.5.0.drv-0/nbconvert-6.5.0
       > Processing ./nbconvert-6.5.0-py3-none-any.whl
       > Requirement already satisfied: entrypoints>=0.2.2 in /nix/store/5l9nyz2lcm7jmcbjm9dn7wdybgbvrn9k-python3.10-entrypoints-0.4/lib/python3.10/site-packages (from nbconvert==6.5.0) (0.4)
       > ERROR: Could not find a version that satisfies the requirement mistune<2,>=0.8.1 (from nbconvert) (from versions: none)
       > ERROR: No matching distribution found for mistune<2,>=0.8.1
       >
       For full logs, run 'nix log /nix/store/33awsap39k9km6mjp244vvqr3i645zw0-python3.10-nbconvert-6.5.0.drv'.
error: 1 dependencies of derivation '/nix/store/n6nhl72pvkajvqvzviwfg2cksrslf3w3-python3.10-jupyterlab-3.4.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3sla8xw6kjm572bnckddppzj8z1rk19i-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/472v9lllp26hxhn51mh3q9v65cw33036-darwin-system-22.11.20220816.0d85bb5+darwin4.80871c7.drv' failed to build

error: builder for '/nix/store/33awsap39k9km6mjp244vvqr3i645zw0-python3.10-nbconvert-6.5.0.drv' failed with exit code 1;
       last 10 log lines:
       > Requirement already satisfied: jupyterlab-pygments in /nix/store/wfhskna566wy5nv76di6bbkc617zavxz-python3.10-jupyterlab_pygments-0.1.2/lib/python3.10/site-packages (from nbconvert==6.5.0) (0.1.2)
       > Requirement already satisfied: bleach in /nix/store/7sdfbc9w7zlm50mgsn4v50zyb8hs28ip-python3.10-bleach-5.0.1/lib/python3.10/site-packages (from nbconvert==6.5.0) (5.0.1)
       > Requirement already satisfied: beautifulsoup4 in /nix/store/nnjdniq8idy2xf0427lsp9czzx9m5ljv-python3.10-beautifulsoup4-4.11.1/lib/python3.10/site-packages (from nbconvert==6.5.0) (4.11.1)
       > Requirement already satisfied: tinycss2 in /nix/store/fnczdkmkr6wx7isjmxjp7bjrdz0fvfs8-python3.10-tinycss2-1.1.0/lib/python3.10/site-packages (from nbconvert==6.5.0) (1.1.0)
       > Requirement already satisfied: nbclient>=0.5.0 in /nix/store/7wnk4c4x8hk6ah74pip6w38l0ddy1vl1-python3.10-nbclient-0.6.6/lib/python3.10/site-packages (from nbconvert==6.5.0) (0.6.6)
       > Requirement already satisfied: traitlets>=5.0 in /nix/store/38ayqs8ajgrx8fvzwmzbw3q5fihb0hvc-python3.10-traitlets-5.3.0/lib/python3.10/site-packages (from nbconvert==6.5.0) (5.3.0)
       > Requirement already satisfied: jupyter-core>=4.7 in /nix/store/3h1jvgw4digg5q0yhq4jvkk9gajklm4l-python3.10-jupyter_core-4.9.2/lib/python3.10/site-packages (from nbconvert==6.5.0) (4.9.2)
       > ERROR: Could not find a version that satisfies the requirement mistune<2,>=0.8.1 (from nbconvert) (from versions: none)
       > ERROR: No matching distribution found for mistune<2,>=0.8.1
       >
       For full logs, run 'nix log /nix/store/33awsap39k9km6mjp244vvqr3i645zw0-python3.10-nbconvert-6.5.0.drv'.
error: 1 dependencies of derivation '/nix/store/n6nhl72pvkajvqvzviwfg2cksrslf3w3-python3.10-jupyterlab-3.4.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3sla8xw6kjm572bnckddppzj8z1rk19i-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/472v9lllp26hxhn51mh3q9v65cw33036-darwin-system-22.11.20220816.0d85bb5+darwin4.80871c7.drv' failed to build

**Comment by PlumpMath** [comment]
https://github.com/NixOS/nixpkgs/issues/187045

**Comment by garbas** [comment]
In next version of jupyterWith (see `main` branch) we are using poetry2nix and this kind of issues wont be happening.
