### ISSUE TITLE
No modules named "pandas" "scipy" and so on

### ISSUE THREAD

**Issue by Lysanleo** [tweag/jupyterWith#283]
**Describe the bug**
I add "pandas", "scipy" to the packages option, and after `nix-shell` I was trying to import them in ipython and notebook.
But the result is the REPL told me that There has no module named such things.
And the matplotlib and numpy I added can be found.
I also checked `$PYTHONPATH`, unfortunately the path of pandas and scipy is not included.

**To Reproduce**
Here is my shell.nix: https://gist.github.com/Lysanleo/de1ab227a8d61567c4bccf4a7c8e87fb

**Expected behavior**
The packages I added can be imported (found).

**Environment**
 - NixOS 22.05:
 - Version of the code: 00dae0df2d86fe78c3666acbdb423ca0ee69f461

**Comment by Lysanleo** [comment]
I found the expected behavior happend until I run `jupyter lab` manually, but what I usually do is getting into the shell and directly run ipython and open the develop directory in vscode and work with an `.ipynb`.
The whole thing works as if the "cache" will refresh only when I rerun `jupyter lab`.

Wonder what to do can simplify the whole thing?

**Comment by djacu** [comment]
Your gist works for me. What did you use to start the environment? I created a `shell.nix` file from your gist and ran: 

`nix-shell --command "jupyter lab"`

https://github.com/tweag/jupyterWith#using-nix-shell

**Comment by djacu** [comment]
There is progress being made on the `main` branch to simplify the process of starting projects. It is not quite ready yet to replace the master branch but should be good to go in a few weeks or less.

**Comment by Lysanleo** [comment]
> Your gist works for me. What did you use to start the environment? I created a `shell.nix` file from your gist and ran:
> 
> `nix-shell --command "jupyter lab"`
> 
> https://github.com/tweag/jupyterWith#using-nix-shell

Yes, I noticed things worked if the `jupyter lab` executed, and you can see  https://github.com/tweag/jupyterWith/issues/283#issuecomment-1242647688 that I'm trying to make things work in a different way. Now I'm confused why the expected behaviour only appear in the `jupyter lab` way and after the way.

**Comment by djacu** [comment]
I think I understand what you are doing but could you verify? Are you running `nix-shell` and then trying to access the kernels in `ipython`?

I'm not very familiar with the way the current code works but it looks like it only exposes the `jupyter-lab` environment and the kernels are wrapped in it. I do not believe it exposes the kernels directly for you to access.

**Comment by Lysanleo** [comment]
> I think I understand what you are doing but could you verify? Are you running `nix-shell` and then trying to access the kernels in `ipython`?
> 
> I'm not very familiar with the way the current code works but it looks like it only exposes the `jupyter-lab` environment and the kernels are wrapped in it. I do not believe it exposes the kernels directly for you to access.

THX for the explan. I may now understand what jupyterWith does for me and how it works a little more. 

I'll try to get the expected result in some other way.

**Comment by djacu** [comment]
We are getting very close to releasing the next version of jupyterWith. I believe you will be able to access the kernels in a python environment then.

**Comment by Lysanleo** [comment]
@djacu THX A LOT. I'll be the first to try.

**Comment by emeinhardt** [comment]
Since the new refactoring has been released, what is the working method for yanking the python executable bundled with a jupyter lab environment out into a `devShell`?
