### ISSUE TITLE
Unable to set config.allowUnfree on the jupyterWith nixpkgs config

### ISSUE THREAD

**Issue by asariley** [tweag/jupyterWith#286]
**Describe the bug**
I added an unfree python package to my jupyterWith environment, and I got the warning that I needed to allow unfree packages, so I added it like so:

    jupyterWith = import (builtins.fetchTarball "https://github.com/tweag/jupyterWith/archive/c71a01a39a3f51951da0dbf0192cf9d1d000151b.tar.gz") {
      overlays = [
        (self: super: {
          python3 = super.python3.override (old: {
            packageOverrides =
              pkgs.lib.composeExtensions
                (old.packageOverrides or (_: _: {}))
                pythonPackageOverrides;
          });
        })
      ];
      config.allowUnfree = true;
    };

however this had no effect and I got the same warning about unfree packages when I rebuilt the configuration. 

**To Reproduce**
1. Add an unfree package to your jupyterWith config
2. Build your configuration and get the warning about this package having an unfree license and refusing to build your config (expected)
3. Pass `config.allowUnfree = true;` to the invocation of the jupyterWith module
4. Build your configuration and get the warning about this package having an unfree license and refusing to build your config (not expected)

**Expected behavior**
I expected adding `config.allowUnfree = true;` where I did, to allow the build to proceed without without getting the unfree error

**Environment**
 - OS: Nixos 22.05
 - Version of the code: https://github.com/tweag/jupyterWith/archive/c71a01a39a3f51951da0dbf0192cf9d1d000151b.tar.gz

**Additional context**
I think this bug was introduced here: https://github.com/tweag/jupyterWith/commit/61c76ed0b0d22ac9f6e53873ec2a57e6bc8fe227

**Comment by djacu** [comment]
Hey @asariley
@garbas submitted https://github.com/tweag/jupyterWith/pull/302 to fix the `config` problem. Pretty sure you were correct about where the bug was introduced.

Try changing your commit SHA to 0e26d3c0026c02bdc5bfdb2a37149d3bdd097eeb and let us know if it works for you.

**Comment by asariley** [comment]
Tried the updated hash and the problem is fixed. Thank you!

**Comment by djacu** [comment]
Glad that it works for you now! I've merged the PR into the `main` branch.
