### ISSUE TITLE
I wish there were Clojure (ClojureScript) and PureScript and TypeScript too

### ISSUE THREAD

**Issue by PlumpMath** [tweag/jupyterWith#301]
https://gist.github.com/bj0/aa1ed75920381144781baa669d0ed4c9

Good day~ :))
Thanks Thanks~

**Comment by djacu** [comment]
The `main` branch has a functioning typescript kernel and will replace the current `master` branch soon.

[ipurescript](https://github.com/Eoksni/ipurescript) and [clojupyter](https://github.com/clojupyter/clojupyter) exist but I do not know if either work. 

I am confused by the gist you linked. It appears to implement a jupyter environment for the coconut language. Was there something there you'd like us to see?

**Comment by djacu** [comment]
Are there particular kernels that you would like to see implemented?

**Comment by PlumpMath** [comment]
https://github.com/Eoksni/ipurescript/issues/1
The creator of ipurescript said that he did not intend to manage it any more.

Of course, the jupyter module that I want to be implemented is ipurescript,
I really hope that everything else mentioned is easy.

**Comment by PlumpMath** [comment]
To be honest, I'm not very good at using jupyter. -_-; Just console repl is convenient, but all languages distribution to nix is possible with jupyter, and I am interested in jupyterhub, and as I do not use jupyter, many more potentials...
It's something I don't know. So, as far as I know, those languages
I am not sure if I will use it in the future. hehe; So I'm not sure what it means to mention, but it would be really nice if something like an emacs mode that shoots something like nbb or babashka was made one by one.
,
of course I am interested in companies and education about production distribution to jupyterhub and nix. (Many developers crash while devops at startup, right?)
.
I hope one day nix and jupyterwith will solve all those problems.
.
yesterday, latest nix's jupyterwith build There is a problem with the build again these days.
