### ISSUE TITLE
[Feature]: Add extraPackages for jupyterlabPoetryEnv

### ISSUE THREAD

**Issue by GTrunSec** [tweag/jupyterWith#325]
### What's missing?

This is necessary when we want to add a plugin to jupyterlab itself, such as jupytext, jupyter-lsp, etc.

### Possible solution

dirty hack here: https://github.com/tweag/jupyterWith/compare/main...GTrunSec:jupyterWith:dev

### Alternatives

also, you can be wrapping the extra pythonPackages.site-packages path to the jupyterLab(without poetry required).

**Comment by djacu** [comment]
Hey @GTrunSec 
Thanks for the issue. Let me know if https://github.com/tweag/jupyterWith/pull/331 provides the fix you need? I think it should and also exposes all the other arguments that `mkPoetryEnv` provides.
