### ISSUE TITLE
Installing package with --extra-index-url

### ISSUE THREAD

**Issue by BenSchZA** [tweag/jupyterWith#34]
I have a package that takes an external repo index URL as an argument to install - `pip3 install _ --extra-index-url _ --user`. Do you have any suggestions about how this can be implemented in jupyterWith?

**Comment by BenSchZA** [comment]
I found a solution/work-around for my issue, by installing locally and adding to Jupyter kernel path in the actual Notebook:

```import sys
sys.path.append("/home/bscholtz/.pip_packages/lib/python3.7/site-packages")```

**Comment by guaraqe** [comment]
The standard way for doing so would be to build a Nix expression to the given package and to put this expression on the dependency list. Actually managing this kind of dependencies using pip would be in the scope of another tool at the Nixpkgs level.

I am glad that you managed to make it work!
