### ISSUE TITLE
Including a local Cabal project via overlays

### ISSUE THREAD

**Issue by MarcFontaine** [tweag/jupyterWith#35]
I want to import a module from a local Haskell-Cabal package via cabal-2-nix.
The package is not part of nixpkgs.
I tried to use the overlay mechanism but had no success.
Could you please add an example or some documentation on how to do this.

**Comment by guaraqe** [comment]
I added an example that calls a local package in the PR #41, can you confirm that this works well for you?

**Comment by MarcFontaine** [comment]
Thanks for your support.
After some debugging I had come up with exactly the same solution.
Hopefully the example will still be useful for others.
(My nix-newbie mistake was that I had used the global `callPackage` instead of `p.callPackage` /
Obvious general `nix` mistake in hindsight and no bug in `jupyterWith` )
