### ISSUE TITLE
Module not found in Python example

### ISSUE THREAD

**Issue by generalized-item** [tweag/jupyterWith#38]
I run the following:

```
git clone https://github.com/tweag/jupyterWith
cd jupyterWith/example/Python/datascience
nix-shell --command "jupyter lab"
```

This opens JupyterLab in my browser. I then create a new Python 3 notebook with a single cell containing

```
import pandas

```

Running this cell yields the following error:

```
ModuleNotFoundError                 Traceback (most recent call last)
<ipython-input-1-38d4b0363d82> in <module>
----> 1 import pandas

ModuleNotFoundError: No module named 'pandas'
```

**Comment by guaraqe** [comment]
I could not reproduce it here. But when you open Jupyter, you have two options for the Python 3 notebook:

- the default one, with no packages
- the "datascience" one, which has all the installed packages defined in the Nix shell

Can you please confirm that you choose the second one?

**Comment by teuffy** [comment]
@guaraqe 
```
nix-shell
jupyter lab
```

I tested it and I confirm it works when you select the approriate kernel  'python 3 - datascience'
