### ISSUE TITLE
Update Jupyter to version 1.x

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#39]
There is work in progress in the Nixpkgs repository here:

- https://github.com/NixOS/nixpkgs/issues/65586
- https://github.com/NixOS/nixpkgs/issues/65625

a PR in progress: https://github.com/NixOS/nixpkgs/pull/67423

**Comment by FRidh** [comment]
this has landed in master 4eed2a56e6a512b184bb614ebfd26658ed11eef4

**Comment by guaraqe** [comment]
Nice, will try update it today.
