### ISSUE TITLE
[Bug]: Publishing up to date doc to netlify fails with Unauthorized

### ISSUE THREAD

**Issue by jaapterwoerds** [tweag/jupyterWith#416]
### Current Behavior

Not all the checkmarks on the master build are green. The one that is fialing is the publishing of documentation

Error: Unauthorized

### Expected Behavior

All checkmarks are green

### Steps To Reproduce

1 Go to the build output of the main branch

### OS

```shell
Happens on CI
```

### Version

master

### Relevant log output

```shell
Run nwtgck/actions-netlify@v2.0
  with:
    production-branch: main
    production-deploy: true
    publish-dir: public
    github-token: ***
    deploy-message: Published from GitHub Actions
    enable-pull-request-comment: true
    overwrites-pull-request-comment: true
    enable-commit-comment: false
    enable-commit-status: true
  env:
    NIX_PATH: nixpkgs=channel:nixpkgs-unstable
    NETLIFY_AUTH_TOKEN: ***
    NETLIFY_SITE_ID: ***
Error: Unauthorized
```

**Comment by djacu** [comment]
Thanks for the bug!
Updated `NETLIFY_AUTH_TOKEN`. Should be fixed now.
