### ISSUE TITLE
Changes to the default package sets

### ISSUE THREAD

**Issue by teuffy** [tweag/jupyterWith#42]
Hi
## A Overlay instructions
Trying google with no success - So I will appreciate help here.
It tried to run nix-buid in the folder nix in order to install the overlays without success.
I am new with nix and jupyterWith
Can you provide the specific instructions to install specific python/haskell/R librairies with nix/python-overlays.nix || nix/haskell-overlays.nix?
Within the python-overlays, an example with fetchgit and one with fetch from local would be more thab welcome.

## B nix-shell with example provided failed.
I did:
``` 
nix-shell example/Haskell/bayesMonad/shell.nix
```
I got this error.

npm ERR!     /build/.npm/_logs/2019-09-15T10_19_30_306Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab-ihaskell" is not a valid npm package
builder for '/nix/store/5x3wj8zijkffvwrrd7f39c88p5k5b8gg-jupyterlab-extended.drv' failed with exit code 1
building '/nix/store/kxy7grqvjn87zdviyz2n8bs6241r12pn-ieee754-0.8.0.drv'...
cannot build derivation '/nix/store/kz3nf9jl8b93pmxaainb8177akw8d42v-python3.7-jupyterlab-0.35.4.drv':
1 dependencies couldn't be built
error: build of '/nix/store/k953hyqsj02rwbn4ayx9kymm1978jh3h-ihaskell-kernel.drv', '/nix/store/kz3nf9jl8b93pmxaainb8177akw8d42v-python3.7-jupyterlab-0.35.4.drv' failed

Christophe

**Comment by guaraqe** [comment]
Hello! For the first problem, I prepared a PR here: https://github.com/tweag/jupyterWith/pull/43. Can you take a look and say if that helps you?

For the second problem, I am not able to reproduce. Can you confirm that you are using the latest master, and if yes, any more details so that I can help?

**Comment by edwardw** [comment]
I tried to follow along your Tweag probabilistic programming with `monad-bayes` blog and build the [notebook](https://github.com/tweag/blog-resources/tree/master/monad-bayes-series) and had a similar error.

A fresh install of `nix` on my Ubuntu box and then:

```bash
$ nix-shell -v
building '/nix/store/5x3wj8zijkffvwrrd7f39c88p5k5b8gg-jupyterlab-extended.drv'...
installing
Node v8.15.0

> /nix/store/35gq5y1l3b5fh0nf95h0izwaiyb7yvwi-nodejs-8.15.0/bin/npm pack jupyterlab-ihaskell
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/jupyterlab-ihaskell failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-09-23T04_51_33_466Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab-ihaskell" is not a valid npm package
builder for '/nix/store/5x3wj8zijkffvwrrd7f39c88p5k5b8gg-jupyterlab-extended.drv' failed with exit code 1
cannot build derivation '/nix/store/9xbbdf7hcgh6sxil2vg6f1js6gfx8gjm-python3.7-jupyterlab-0.35.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/9xbbdf7hcgh6sxil2vg6f1js6gfx8gjm-python3.7-jupyterlab-0.35.4.drv' failed
```

I run the latest Ubuntu 19.04 if that matters:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by guaraqe** [comment]
There is a good chance that it is Nix sandbox by default that is stopping that. Can you try:

```
nix-shell --option build-use-sandbox false
```

There are more details in the README if you search for sandbox.

**Comment by edwardw** [comment]
Works like a charm! Thanks, @guaraqe.

**Comment by teuffy** [comment]
```
nix-shell --option build-use-sandbox false
```

produce the same error message

```
installing
Node v8.15.0

> /nix/store/35gq5y1l3b5fh0nf95h0izwaiyb7yvwi-nodejs-8.15.0/bin/npm pack jupyterlab-ihaskell
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/jupyterlab-ihaskell failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-09-23T06_48_52_396Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab-ihaskell" is not a valid npm package
builder for '/nix/store/5x3wj8zijkffvwrrd7f39c88p5k5b8gg-jupyterlab-extended.drv' failed with exit code 1
building '/nix/store/w6aqrg5v3v6mr8jd4dsab4y1ksnsra9z-monad-parallel-0.7.2.3.drv'...
cannot build derivation '/nix/store/kz3nf9jl8b93pmxaainb8177akw8d42v-python3.7-jupyterlab-0.35.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/k953hyqsj02rwbn4ayx9kymm1978jh3h-ihaskell-kernel.drv', '/nix/store/kz3nf9jl8b93pmxaainb8177akw8d42v-python3.7-jupyterlab-0.35.4.drv' failed

```

**Comment by guaraqe** [comment]
Can you try the second method that is in the README, setting `build-use-sandbox = false` in `/etc/nix/nix.conf`?

**Comment by teuffy** [comment]
> Hello! For the first problem, I prepared a PR here: #43. Can you take a look and say if that helps you?
> 
> For the second problem, I am not able to reproduce. Can you confirm that you are using the latest master, and if yes, any more details so that I can help?

1. first problem: havenot tried yet but will do.

2. second problem

- [ here is the error message]

```
nix-shell
error: attribute 'haskellPackages' missing, at /home/user/folder/shell.nix:14:21
(use '--show-trace' to show detailed location information)
```

- [ here is my shell.nix]
```
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "";
  }) {};

  alphaVantageSrc = jupyter.fetchFromGitHub {
     owner = "pshemass";
     repo = "alpha-vantage-haskell";
     rev = "201d9925228f6ee40b346e20036944814dcb95d3";
     sha256 = "12qpwfgsb6vgcbl0xwr95pwsrqvd2jk3qdc9cfwjppdjfr78br4q";
     };

  haskellPackages = jupyter.haskellPackages.override (old: {     # this is line 14
    overrides = jupyter.lib.composeExtensions old.overrides
        (self: hspkgs: {
          alpha-vantage-haskell = hspkgs.callCabal2nix "alpha-vantage-haskell" "${alphaVantageSrc}" {};
        });
      });

  ihaskell = jupyter.kernels.iHaskellWith {
    haskellPackages=haskellPackages;
    name = "haskell";
    packages = p: with p; [ hvega formatting hmatrix alpha-vantage-haskell ];
  };

  ipython = jupyter.kernels.iPythonWith {
    name = "python";
    packages = p: with p; [ numpy pandas matplotlib seaborn opencv pytorch scipy scikitlearn xgboost tensorflow-tensorboard k\
eras-applications mysql-connector google_api_python_client sklearn-deap ipywidgets pprintpp virtualenvwrapper beautifulsoup4 \
requests html5lib memory_profiler jupyter_console statsmodels google_cloud_bigquery quandl pillow ];
  };

  jupyterEnvironment =
   jupyter.jupyterlabWith {
    kernels = [ ihaskell ipython ];
    directory = ./jupyterlab;
  };
in
  jupyterEnvironment.env

**Comment by guaraqe** [comment]
Can you try using the model for external packages that I showed in the PR? It should solve your problem.

In this case, it does not help because `jupyter` is not `nixpkgs`, you can have `nixpkgs` by following the model in some of the examples, by importing the `nix` folder.

**Comment by teuffy** [comment]
> Can you try using the example for external packages that I showed in the PR? It should solve your problem.
> 
> In this case, it does not help because `jupyter` is not `nixpkgs`, you can have `nixpkgs` by following the model in some of the examples, by importing the `nix` folder.

I tried the #43 pull request for internal/local package for python and it works. 
I can't see a PR for external package in the PR.
