### ISSUE TITLE
Cachix not up-to-date

### ISSUE THREAD

**Issue by curiousleo** [tweag/jupyterWith#49]
It looks like jupyterwith.cachix.org does not contain a cached build for the latest `master` commit, 7929eceafe2f59257c089707d2130570cf22a8dc.

I am using the `jupyterwith` Cachix cache. Opening a `nix-shell` using https://github.com/tweag/blog-resources/blob/master/monad-bayes-series/shell.nix still takes forever, and it is clearly building lots of Jupyter-related things.

Related: https://github.com/tweag/jupyterWith/issues/12

**Comment by curiousleo** [comment]
(Note that pushing to Cachix can be done in CI, e.g. https://github.com/tweag/funflow/blob/e469d434073455324db1ed7bec5df260958dc83e/.circleci/config.yml#L19)

**Comment by guaraqe** [comment]
Nixpkgs version was updated, and Cachix was loaded with it.
