### ISSUE TITLE
Document how to add additional packages to the environment, such as pandoc

### ISSUE THREAD

**Issue by marcus7070** [tweag/jupyterWith#52]
I use jupyterWith through this `shell.nix`:
```nix
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "";
  }) { };

  iPython = jupyter.kernels.iPythonWith {
    name = "numpy";
    packages = p: with p; [
      numpy
      bokeh
    ];
  };

  jupyterEnvironment = jupyter.jupyterlabWith {
    kernels = [ iPython ];
    directory = jupyter.mkDirectoryWith {
      extensions = [
        "jupyterlab_bokeh"
      ];
    };
  };

in
  jupyterEnvironment.env
```
and activate the environment with `nix-shell --option sandbox false --command "jupyter lab"`.

When I try to export a notebook to a PDF, my browser shows an error that pandoc is not installed.

I can't figure out how to get pandoc into my jupyterWith environment. This seems like a common task, perhaps suitable for documenting in the readme?

**Comment by guaraqe** [comment]
There is currently no default way, but it is simple enough to allow JupyterWith to do that, I will prepare a PR.

**Comment by guaraqe** [comment]
I merged a PR that adds the functionality you wanted, look at the commit for an example on how to use it: https://github.com/tweag/jupyterWith/pull/55

**Comment by marcus7070** [comment]
Thanks @guaraqe, but when I try e29ce461a2445118fdc791126533d60899a75937 I get
```
error: 'jupyterlabWith' at /nix/store/7s6wjdfq94cw858bmwrlmyqmfgs8wgzs-source/default.nix:22:20 called with unexpected argument 'extraPackages', at /home/marcus/shell.nix:20:24
```

Should this: https://github.com/tweag/jupyterWith/blob/e29ce461a2445118fdc791126533d60899a75937/default.nix#L22 
actually be something like this? 
```nix
jupyterlabWith = { directory ? defaultDirectory, kernels ? defaultKernels, extraPackages ? (p: [ ]) }:
```

**Comment by guaraqe** [comment]
The version that would work is:

```
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "e29ce461a2445118fdc791126533d60899a75937";
  }) { extraPackages = p: [p.pandoc] };
```

but I agree that what you expected is more natural. It is a little more modular too. I will adapt it.

**Comment by guaraqe** [comment]
The PR has been merged, I realized the documentation said what you tried. Thank you for the catch!
