### ISSUE TITLE
Rust kernel: evcxr support via evcxr_jupyter

### ISSUE THREAD

**Issue by evanjs** [tweag/jupyterWith#59]
Is there any interest in adding support for [`evcxr_jupyter`](https://github.com/google/evcxr/tree/master/evcxr_jupyter)?
It looks like it has some [quirks](https://github.com/google/evcxr/blob/454475ec04dac87706d22d9140f7a88e59a94e43/evcxr_jupyter/README.md#usage-notes), but I think it would be a nice addition to this project.

`evcxr` is [in tree](https://github.com/NixOS/nixpkgs/blob/0c9fab9398bb682b2e317a5d7e65b6c171d4c5be/pkgs/development/interpreters/evcxr/default.nix) already, though `evcxr_jupyter --install` needs to be run after `evcxr` is installed.

**Comment by guaraqe** [comment]
It is certainly interesting for us! I will put it on the TODO list, but if someone wants to give a try a propose a PR, we are open!

**Comment by kristoff3r** [comment]
Added in #107
