### ISSUE TITLE
Make libraries accessible outside of Jupyter

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#61]
It would be nice to define a JupyterWith environment and be able to:

- have libraries accessible on Jupyter
- have libraries accessible on the shell, with `python` or `ghci`, for example.

This should not be too hard in the Python and Haskell cases.

One question that arises is how to manage a shell where there are multiple concurrent kernels for the same language. The solution I see for the moment is to create different wrapping executables called `python-$KERNEL_NAME` or `ghci-$KERNEL_NAME`, which access the correct environments.

**Comment by ariutta** [comment]
It appears this was completed in commits b9280bc2d62badcf687d50cb8b2dcfd062e0dac4 and 31f49b66bc2f07230f6bd27436eb21f77241d4c9?

**Comment by guaraqe** [comment]
Yes, this was completed for Haskell and Python, closing this now. We will open further isses if needed for other languages, since there is no uniform strategy that works for all.
