### ISSUE TITLE
Jupyterhub?

### ISSUE THREAD

**Issue by dpavlic** [tweag/jupyterWith#69]
This overlay is an extremely important 'path forward' for us; we are evaluating nixos to simplify our data science stack, and jupyter + extensions has been one of the pain points. While jupyterWith solves this, we actually need a system wide multi-user implementation utilizing jupyterhub. Since we are still very much newbies, we are wondering if there is any way we can utilize the maturity of jupyterWith, but using it to deploy a 'batteries included' jupyterhub configuration?

**Comment by guaraqe** [comment]
We touch the subject fast in the release blog post: https://www.tweag.io/posts/2019-02-28-jupyter-with.html. The idea is to generate a Docker image with the desired JupyterWith configuration, and to release it to JupyterHub. We cover the generation of Docker images here: https://github.com/tweag/jupyterWith#building-the-docker-images

**Comment by garbas** [comment]
We are currently cleaning up the implementation in `master` (see `main` branch). We have some rough plans to also to be able to deploy as jupyterhub service, but there are few other things we need to sort out before that.
