### ISSUE TITLE
Progression towards a stable release

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#71]
This is a action plan towards having a stable JupyterWith. The ideal goal of this plan is to have:

- **JupyterWith as a part of Nixpkgs**. Having JupyterWith as an external package makes it more flexible, but creates a continuous mismatch between Nixpkgs and us. Having this as the default interface for Nixpkgs would make it more accessible, and maintenance more progressive.

- **Extensions customizable at will**. Using JupyterWith should not be a barrier to any use of Jupyter. All extensions should be accessible, even if through the use of an escape hatch.

- **A ready-to-use package set for data science**. In Python and maybe Haskell. The main public of Jupyter Notebooks are data scientists, so there should be as little friction as possible for this use case.

The third point is kinda orthogonal to other points, and is covered by issue #62. For the other two points, the proposed steps are:

1) **Create a standard set of lab and server extensions.** This amounts to make a `generate-folder` with adequate parameters, and to stock this folder somewhere. The README should make clear that using only the default extensions lead to the most stable behavior. This should solve the problem of most users opening issues in this repository. #72 

2) **Setup the standard set of extensions using Nix.** When generating the JupyterLab folder, a `yarn.lock` file is created. We should be able to use `yarn2nix` to generate an appropriate Jupyter folder using only this file. This would open the door for adding JupyterWith to Nixpkgs, since we would have no external dependencies. #73

3) **Make the procedure above accessible to users.** It should be easy for users to reproduce the procedure above, and to be able to setup their own JupyterLab distribution using a `yarn.lock` generated by JupyterLab.

4) **Declarative setup of extensions.** This would allow to use any extension declaratively from a Nix expression. This could take two forms. The first is having some kind of Jupyter LTS package set of extensions. The second is collaborating with Jupyter folks so that Nix can be used as a determinist package manager, and to be able to fix versions of all packages easily.

This issue is here so we can follow progress, the actual work will happen in other issues.

**Comment by guaraqe** [comment]
Since #73 is closed, we can proceed with #72 and establish the set of extensions we want by default.

**Comment by guaraqe** [comment]
It seems that step 4 is not actually possible, at least as thought before. The reason for this is that Jupyter treats the JupyterLab folder as mutable - even enabling or disabling extensions involve writing files on it. It is possible to generate the `static` folder using Nix, but that involves pointing to it from a mutable folder, which does not seem to be very advantageous.

Therefore, the next steps are:

1) **Select a standard set of lab and server extensions.** This selection will result in two lockfiles that will give the default Jupyter folder. This will be an immutable folder, with all extensions enabled, so much care must be taken with their choice.

2) **Prepare the PR in Nixpkgs.** This PR will focus on have the same functionality of JupyterWith from inside Nixpkgs. The default Jupyter folder will be the one generated by the lockfiles mentioned above. Some difficulties I foresee are:

    - Dealing with Python and Haskell overrides. Should they be setup locally or globally?
    - Dealing with Python and Haskell versions. Should they be fixed or configurable at will?

    The expected user experience is:

    - Out of the box, all kernels and default extensions should work well. Any necessary overrides should be possible to be done via local overlays to Nixpkgs, as it is usual for other packages.
    - If the user needs other sets of extensions, they should generate the folder manually. The Nix shell should give the tools so that this procedure is as easy as possible.

**Comment by garbas** [comment]
Working on new roadmap, PR soon to come.
