### ISSUE TITLE
Establish the Jupyter extensions to be shipped by default

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#72]
We want to have a default Jupyter Lab folder that is well-suited to most applications to be the default ones. This amounts to choosing a set of extension for which we will generate a folder and upload somewhere. The goal of this issue is to determine this set.

A pointer is the following link, showing the set of Jupyter extensions sorted by popularity: https://www.npmjs.com/search?q=keywords%3Ajupyterlab-extension&ranking=popularity

Another is the "awesome" repo for Jupyter Lab extensions: https://github.com/mauhai/awesome-jupyterlab

An aspect that should also be taken into account are extensions that are necessary (or very useful) for using some of the kernels we have, such as IHaskell.

**Comment by alexvorobiev** [comment]
This would be very valuable. We use Nix to provide up to date tools to data scientists who are not developers. They all use the default profile where everything is preconfigured.

**Comment by djacu** [comment]
captured in the roadmap
