### ISSUE TITLE
Find a way to generate a Jupyter folder from a single file

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#73]
We want to be able to eventually merge this repository into Nixpkgs. Therefore, we must find a way to make compatible #72 (default set of extensions) and the fact that Nixpkgs will not accept to have neither the full JupyterLab folder in the repository, neither a link given by us pointing to this folder uploaded somewhere.

Our current best pointer is to use the `yarn.lock` generated by Jupyter during the installation of extensions to reverse-engineer the Jupyter folder. The difficulties are:

- It is not completely clear how to generate the Jupyter folder using just the `node_modules` folder. There are Javascript files that mention explicitly the names of installed extensions.

- When installing extensions, Jupyter downloads a version it considers good, and keep it inside a local folder. The lock files does not refer to a particular version of the extension, but to this local copy of the extension.

This issue will follow the progress towards this goal.

**Comment by guaraqe** [comment]
The best I got until now is:

- Generate the folder as usual, and recover the `yarn.lock` file.
- Change manually the entries for local extensions to their remote versions in NPM, so that there are no mentions to local folders.
- Generate manually the folder hierarchy and move the `yarn.lock` file to the `staging` folder.
- Use `jupyter lab build --app-dir $DIRECTORY` to build the folder.

This is interesting because it should build the folder in a deterministic way, since it only depends on the `yarn.lock` file. However, it still makes network requests, for which sandbox mode should be disabled.

The next is step is to figure out a way of separating fetching and building.

**Comment by guaraqe** [comment]
I tried writing the function that calls `jupyter lab build` as a Nix fetcher. However, I am facing a problem, where the behavior of `nix-build --option sandbox false` and `nix-build` is not the same, even in the case of a fetcher. This seems related to:

> If chroots are enabled, they are now used for all derivations, including fixed-output derivations (such as fetchurl). The latter do have network access, but can no longer access the host filesystem. If you need the old behaviour, you can set the option build-use-chroot to relaxed.

**Comment by guaraqe** [comment]
It seems that "host filesystem" above means everything outside `$TMP` (that is, `/build` from the builder perspective) and `$out`, that is in the Nix store. Therefore, it is possible that `jupyter` is trying to access other folders.

**Comment by guaraqe** [comment]
The errors I am seeing are:

```
$ /build/folder/staging/node_modules/.bin/yarn-deduplicate -s fewer
/bin/sh: /build/folder/staging/node_modules/.bin/yarn-deduplicate: not found
```
and
```
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
/bin/sh: ensure-max-old-space: not found
```

The first error is strange, since when I enter inside the build folder using `breakpointHook`, I am able to execute the command. I thought that the problem could be `/bin/sh` not being accessible, but this is not the problem.

**Comment by guaraqe** [comment]
I managed to solve the problem. The problem was that files generated by `npm` used the `/usr/bin/env node` interpreter. Changing all node executables interpreter to the node in Nixpkgs did the job.

The current branch is able to build a JupyterLab folder. The next steps are:

- Test multiple Jupyter Extensions using this method.
- Add a dedicated example so it can be tested easily.
- Build the same derivation in multiple machines to make sure it is indeed determinist.

**Comment by guaraqe** [comment]
Another problem appeared - extensions in the Lockfile do not appear. It seems that the correct place to change `yarn.lock` and `package.json` is in the source of the `jupyter-lab` executable, not in the destination folder: https://discourse.jupyter.org/t/notes-on-jupyterlab-build/541/8

I think that by doing this, complemented with the method devised above, I should solve the problem, this is my next test.

**Comment by guaraqe** [comment]
The above didn't work. What seemed to work was:

- To take an existing working JupyterLab folder, and replace the yarn.lock and package.json files.
- Do `jlpm install` and `jlpm build`.

However, when opening Jupyter, it complains about the extension that is installed.

**Comment by guaraqe** [comment]
The last iteration seems to work. Extensions show in the Jupyter Lab UI, however, there is still a warning message asking for a Jupyter Build. I have to find a way to remove this warning. The code that produces the message is here: http://pydoc.net/jupyterlab/0.31.1/jupyterlab.commands/

**Comment by aspiwack** [comment]
Maybe you have gathered enough data, and it is time to get in contact with Jupyterwith folks to see if they have some opinion on that, or if a change upstream could facilitate this line of work?

**Comment by guaraqe** [comment]
It is difficult to propose something now, since they are also struggling with their own build system. Some related issues:

- https://discourse.jupyter.org/t/notes-on-jupyterlab-build/541
- https://github.com/jupyterlab/jupyterlab/issues/5672
- https://github.com/jupyterlab/jupyterlab/issues/4439
- https://github.com/jupyterlab/jupyterlab/issues/7525

**Comment by guaraqe** [comment]
I confirm that extensions work using this method. I have two choices concerning it:

- The first is to install everything using `jlpm`. In this case we get a warning saying "An extension shoud be removed". There are no buttons to enable or disable extensions.

- The second is to do the same, but copy the source for the extension from `node_modules` to the `extensions` folder in the Jupyter Lab folder. This changes the warning to "An extension changed locations." There are buttons to enable or disable extensions, however, they do not work, since the JupyterLab folder is immutable, and settings are stored in it.

I will see now if I can do something about warnings. If that is solved, I will consider the issue as closed.

**Comment by TethysSvensson** [comment]
Would it be possible to supply some documentation for how to use this feature? I've been trying to get it to work, but I a `TypeError: Cannot convert undefined or null to object` in `staging/webpack.config.js:26:10` in the webpack stage.
