### ISSUE TITLE
Make sure JupyterWith works on Mac

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#74]
This should make part of the stable release process.

**Comment by qnikst** [comment]
Current master fails to build ipython kernel due to https://github.com/NixOS/nixpkgs/issues/76197. Using more recent Nixpkgs from Darwin branch fixes that issue. I've used:

```Haskell
  src = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/c23427de0d501009b9c6d77ff8dda3763c6eb1b4.tar.gz";
    sha256 = "0fgv4pyzn39y8ibskn37x9cabmg6gflisigr5l45bkplm06bss91";
  };
```

**Comment by guaraqe** [comment]
I added CI for MacOS, closing.
