### ISSUE TITLE
Iscala kernel

### ISSUE THREAD

**Issue by xy2iii** [tweag/jupyterWith#80]
Hello!

I use nixOS a lot and it would be nice to have a Scala kernel for Jupyter.

Thank you very much!

**Comment by rodfersou** [comment]
why not BeakerX instead? http://beakerx.com/ have all those kernels:

> Groovy, Scala, Clojure, Kotlin, Java, and SQL, including many magics;

**Comment by MarkRBM** [comment]
I would also love a scala kernel to be available.  I have looked at the kernel examples but dont immediately see how I would create a derivation to get https://almond.sh/ working on jupyterWith

I have tried to install beakerx as an extension but it fails and says beakerx is not compatible with this version of jupyterlab

**Comment by garbas** [comment]
We've added iscala to our roadmap (soon to be commited to `main` branch).
