### ISSUE TITLE
How can I fix npm fetch SSLCertVerificationError ?

### ISSUE THREAD

**Issue by GTrunSec** [tweag/jupyterWith#85]
**SSLCertVerificationError**
![image](https://user-images.githubusercontent.com/21156405/80199106-d4075500-85d5-11ea-8447-ae95e5fc5e25.png)

Platform: osx
test env : https://github.com/GTrunSec/analysis-arg-lab/blob/master/osx-env.nix
`ihaskell_labextension` for Jupyterlab version 2.0 later.

**Comment by guaraqe** [comment]
This seems related to the sandbox network access. You have two choices:

- RECOMMENDED: Generate the JupyterLab folder manually.
- Disable the sandbox in Nix.

These options are described here: https://github.com/tweag/jupyterWith#using-jupyterlab-extensions

**Comment by GTrunSec** [comment]
Thank you for help.
I'm going to your first option.
also, I can surely this problem does not relate sandbox.

**Comment by GTrunSec** [comment]
I have done it for the test.  the ihaskell_labext doesn't work on Jupyter lab 2.

![image](https://user-images.githubusercontent.com/21156405/80210254-4d0fa800-85e8-11ea-895f-8d2c04397ade.png)


https://github.com/gibiansky/IHaskell/pull/1151
