### ISSUE TITLE
Checkout Jupyter 2.1.0

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#91]
The new release has an embedded extension manager, that may or may not improve our life. If the only thing it does is manage extensions on the JupyterLab folder from the frontend, the situation doesn't change. Otherwise, maybe we can make some things simpler.

Link: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v2-1-0

**Comment by GTrunSec** [comment]
yes, Jupyter-lab 2.1.0 has embedded extension manager. you can install and rebuild an extension in Jupyterlab manager. But the Haskell syntax will not work in 2.1.0. https://github.com/gibiansky/IHaskell/issues/1159 also, you can do a test to ensure this problem.

**Comment by garbas** [comment]
In `main` branch we are using latest jupyterlab and we will always follow latest release.
