### ISSUE TITLE
[Doc Request] Adding "more recent" python packages to kernel environment

### ISSUE THREAD

**Issue by mdtisdall** [tweag/jupyterWith#95]
As a new nix user, the current documentation doesn't help me fully understand how to use the overlay process to add a python package to my environment that are only available "more recently" than nixpkgs version pinned by jupyterWith. I've tried looking at the relevant issues, the NixOS docs on overlays, and the jupyterWith documentation which shows an example overlay. The examples for setting up a `shell.nix` file without overlays are very clear, but I think the overlay part is too brief. Some questions I'm left with:

1) Does this overlay example go in a separate file? Where is it saved normally?
2) How do I modify my `shell.nix` file to use this overlay?
3) Is there a simpler way to import "more recent" packages so an iPython kernel can "see" them?

Can someone please expand on this documentation to concretely help newbies solve this problem?

**Comment by GTrunSec** [comment]
please see my example and environment: https://github.com/GTrunSec/Jupyter-data-science-environment/blob/768d4660050b14b9a63dc2681d96a9407f7a5f2c/default.nix#L16

**Comment by mdtisdall** [comment]
Thanks for your help. I've tried to follow the example you shared but I admit I'm a little lost. My basic `shell.nix` is:

```
let
  jupyter = import( builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
  }) {};

  
  iPython = jupyter.kernels.iPythonWith {
    name = "notebook";
    packages = p: with p; [
      numpy
      matplotlib
      nibabel
      boto3
    ];
  };

  iRKernel = jupyter.kernels.iRWith {
    name = "notebook";
    packages = p: with p; [
      cowplot
      dplyr
      ggplot2
    ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [
        iPython
        iRKernel
      ];
      directory = ./jupyterlab;
      extraPackages = p: [
        p.python3Packages.jupytext
      ];
      extraJupyterPath = p: "${p.python3Packages.jupytext}/lib/python3.7/site-packages";
    };
in
  jupyterEnvironment.env
```

Following your example, I modified this to

```
let
  jupyter = import( builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
  }) {};


  pkgs = (import (jupyter + "/nix/nixpkgs.nix")) { config={ allowUnfree=true; allowBroken=true; };};


  iPython = jupyter.kernels.iPythonWith {
    name = "notebook";
    packages = import ./overlay/python-list.nix { inherit pkgs;};
  };

  iRKernel = jupyter.kernels.iRWith {
    name = "notebook";
    packages = p: with p; [
      cowplot
      dplyr
      ggplot2
    ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [
        iPython
        iRKernel
      ];
      directory = ./jupyterlab;
      extraPackages = p: [
        p.python3Packages.jupytext
      ];
      extraJupyterPath = p: "${p.python3Packages.jupytext}/lib/python3.7/site-packages";
    };
in
  jupyterEnvironment.env
```

and created `overlay/python-list.nix` containing:

```
{pkgs}:
let
## more recent rev nixpkgs
   nixpkgs =  import <nixpkgs> {};
in
(with pkgs.python3.withPackages;
        (p: with p;  [
                numpy
                matplotlib
                nibabel
                boto3
    nixpkgs.python3Packages.pydicom
  ]))
```

However, when I run `nix-shell` I still get `error: attribute 'pydicom' missing, at /home/dylan/notebook/overlay/python-list.nix:12:5`. I believe that pydicom is a supported python3 package in nixpkgs.

Any further suggestion for how to add it? Am I completely misdiagnosing the problem?

**Comment by GTrunSec** [comment]
Sorry. It won't work in my first solution.
try this solution.
```
{ python3, pkgs }:
let
  my-overlay  = builtins.fetchGit {
    url = "https://github.com/hardenedlinux/NSM-data-analysis";
    rev = "07a94f1f8a154e0aa4e9f9675014d663e91a73de";
  };
  nixpkgs =  import <nixpkgs> {};
in
python3.override {
  packageOverrides = self: super: rec {
    editdistance =  self.callPackage "${my-overlay}/pkgs/python/editdistance" {};
    jupyterlab_git =  self.callPackage ./pkgs/jupyterlab-git {};
    own-pydicom =  self.callPackage (<nixpkgs> + "/pkgs/development/python-modules/pydicom") { };
    own-geoip2 =  self.callPackage (<nixpkgs> + "/pkgs/development/python-modules/geoip2") { };
  };
}

```
{pkgs}:
(with pkgs.python3.withPackages; (p: with p;  [ jsondiff
                                                geoip2
                                                numpy pandas matplotlib editdistance ipywidgets
                                                graphviz pillow elasticsearch requests sqlalchemy
                                                qtconsole
                                                own-pydicom
                                                own-geoip2
                                              ]))
```

```

**Comment by GTrunSec** [comment]
Override dependence example:
https://github.com/GTrunSec/Jupyter-data-science-environment/blob/9c9ac32a7a2dd696343059ace7911e206faea410/overlay/python-list.nix#L8

**Comment by mdtisdall** [comment]
Thanks again for the help, but I'm still not quite there. In my effort to keep the changes minimal perhaps I've broken something. I now have `shell.nix`:

```
let
  jupyter = import( builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
  }) {};


  pkgs = (import (jupyter + "/nix/nixpkgs.nix")) { config={ allowUnfree=true; allowBroken=true; };};


  iPython = jupyter.kernels.iPythonWith {
    name = "notebook";
                python3 = pkgs.callPackage ./overlay/own-python.nix { inherit pkgs;};
    packages = import ./overlay/python-list.nix { inherit pkgs;};
  };

  iRKernel = jupyter.kernels.iRWith {
    name = "notebook";
    packages = p: with p; [
      cowplot
      dplyr
      ggplot2
    ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [
        iPython
        iRKernel
      ];
      directory = ./jupyterlab;
      extraPackages = p: [
        p.python3Packages.jupytext
      ];
      extraJupyterPath = p: "${p.python3Packages.jupytext}/lib/python3.7/site-packages";
    };
in
  jupyterEnvironment.env
```

`overlay/own-python.nix`:
```
{ python3, pkgs }:
let
  nixpkgs =  import <nixpkgs> {};
in
python3.override {
  packageOverrides = self: super: rec {
    own-pydicom = self.callPackage (<nixpkgs> + "/pkgs/development/python-modules/pydicom") { };
  };
}```

and `overlay/python-list.nix`
```
{pkgs}:
(with pkgs.python3.withPackages;
        (p: with p;  [
                numpy
                matplotlib
                nibabel
                boto3
                own-pydicom
  ]))```

However when I run `nix-shell` I'm getting the error: `rror: cannot coerce a set to a string, at /home/dylan/notebook/shell.nix:7:19`.

Any further advice on what I've got wrong here?

**Comment by GTrunSec** [comment]
```
let
  jupyterLib = builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "dc8bb19f3f850c903fe481cbc7efc0982e6afd28";
    ref = "master";
  };

  overlays = [
    # Only necessary for Haskell kernel
    (import ./overlay/python.nix)
  ];

  pkgs = (import (jupyterLib + "/nix/nixpkgs.nix")) { inherit overlays; config={ allowUnfree=true; allowBroken=true; };};
  jupyter = import jupyterLib {pkgs=pkgs;};

  iPython = jupyter.kernels.iPythonWith {
    name = "notebook";
    python3 = pkgs.callPackage ./overlay/own-python.nix { inherit pkgs;};
    packages = import ./overlay/python-list.nix { inherit pkgs;};
  };

  iRKernel = jupyter.kernels.iRWith {
    name = "notebook";
    packages = p: with p; [
      cowplot
      dplyr
      ggplot2
    ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [
        iPython
        iRKernel
      ];
      directory = ./jupyterlab;
      extraPackages = p: [
        p.python3Packages.jupytext
      ];
      extraJupyterPath = p: "${p.python3Packages.jupytext}/lib/python3.7/site-packages";
    };
in
  jupyterEnvironment.env

```

**Comment by GTrunSec** [comment]
@mdtisdall  https://github.com/GTrunSec/Jupyter-data-science-environment/blob/master/shell-test.nix

**Comment by mdtisdall** [comment]
Thanks, this was very helpful and I was eventually able to get it working following your example (and upgrading to NixOS 20.03 where pydicom is in the standard nixpkgs).

I'll call this closed, and just note that I at least couldn't have done this just off the docs, but I'm also not really knowledgeable enough to improve the docs myself.

**Comment by guaraqe** [comment]
@mdtisdall JupyterWith has an `overlays` argument, which is supposed to avoid the pain you had with importing `nixpkgs.nix`, and etc. It is supposed to be used as (taking the example above as reference):

```
let
  jupyterSrc = builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "dc8bb19f3f850c903fe481cbc7efc0982e6afd28";
    ref = "master";
  };

  jupyter = import jupyterSrc {
    overlays = [ (import ./path/to/your/overlay.nix) ];
  };

  ...

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [
        iPython
      ];
    };
in
  jupyterEnvironment.env
```

I agree this is very badly documented in the README. Can you confirm that the pattern here works for you? If this is ok, I will add a section to the README better explaining this.
