### ISSUE TITLE
Make JupyterWith a Flake

### ISSUE THREAD

**Issue by guaraqe** [tweag/jupyterWith#99]
It was proposed in #79 that JupyterWith could be a Flake, instead of merging it in Nixpkgs. At the time I didn't understand well what that meant, but since the [release](https://www.tweag.io/posts/2020-05-25-flakes.html) I see better why that makes sense:

- A Flake would make the outputs and inputs of JupyterWith explicit, making it more discoverable. We want our public to consist on more than Nix enthusiasts, so this is very important.

- We could eventually add JupyterWith to the Flake registry, which would make using it much simpler. Once more, this makes its adoption easier.

The approach I want to take has two steps:

- First, write the `flake.nix` file, and structure it in a way that seems appropriated. This will maybe demand some internal refactorings. However, the goal is to not change the JupyterWith interface. That is, `default.nix` stays the same.

- In a second moment, when the flake seems to work well, replace the `default.nix` by one that uses `flake.nix`. This can be done in a backwards-compatible way using [flake-compat](https://github.com/edolstra/flake-compat). An example of its usage is [here](https://github.com/NixOS/nixos-homepage/blob/master/default.nix).

This is connected to #71.

**Comment by guaraqe** [comment]
Reference on the file format: [RFC](https://github.com/NixOS/rfcs/blob/8c36f764fbae6a09b06fe2a35b5828e79e24d950/rfcs/0049-flakes.md).

**Comment by teto** [comment]
having a flake would be nice indeed.

**Comment by GTrunSec** [comment]
I'm ready to add the feature of flake for juyterWith

**Comment by teto** [comment]
Please do it, even if it is not merged, I will use it :D

**Comment by guaraqe** [comment]
> I'm ready to add the feature of flake for juyterWith

If you are interested, open an issue describing the interface you would use for the flake, and we can discuss there. I think that the architecture of the outputs is the trickiest part for this conversion.

**Comment by GTrunSec** [comment]
please check PR for flake https://github.com/tweag/jupyterWith/pull/158

**Comment by rofrol** [comment]
Can it be closed?
